### ISSUE TITLE
Weird error running the example

### ISSUE THREAD

**Issue by EugeneLiang** [DracoBlue/node-facebook-client#6]
Hi, 
I got a weird error running the example. The error message was:

node.js:183
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'facebook-client'
    at Function._resolveFilename (module.js:322:11)
    at Function._load (module.js:267:25)
    at require (module.js:367:19)
    at Object.<anonymous> (/home/eugene/public_html/nodejs/examples/DracoBlue-node-facebook-client-1fe4a7e/run_example.js:2:22)
    at Module._compile (module.js:423:26)
    at Object..js (module.js:429:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at Array.<anonymous> (module.js:442:10)
    at EventEmitter._tickCallback (node.js:175:26)

May i know why is facebook-client missing?

I simply downloaded node-facebook-client and extracted it into a folder, than ran the example after changing the appid and secret.

I'm using node-facebook-client v1.3.0 and node.js version 0.5.0-pre ( the latest version as of today ).

Am i missing anything?

**Comment by EugeneLiang** [comment]
oh, i've tried running the example with node version 4.7 and it didnt work too.

I've also tried placing run_example.js in the /lib folder but it didnt work as well.

Best.

**Comment by DracoBlue** [comment]
Hi,

you have to replace require("facebook-client") with require("./node-facebook-client/lib"), if you are not using npm install facebook-client.

Regards,
  Jan

**Comment by EugeneLiang** [comment]
ok got it!
